### ISSUE TITLE
Bug report: "Extract texture images into the folder" option doesn't work properly

### ISSUE THREAD

**Issue by alaborde29** [saturday06/VRM-Addon-for-Blender#453] opened 2024-04-07 14:29 UTC
## Describe the bug

When i import a vrm file into blender and choose the Ectract texture images into the folder option, it does create a folder that instantly disapear

## To Reproduce

same as above

## Expected behavior

A creation of a folder with vrm texture files

## Desktop 

- OS: Windows AND macOs
- Blender 2.93, 3.x, 4.x
- Addon Version: latest

**Comment by saturday06** [comment] 2024-04-07 16:30
Thanks for reporting!
The error was resolved with the latest add-on released a while ago. Please try!

**Comment by alaborde29** [comment] 2024-04-07 16:39
i think there's still some issue with this feature. i managed to make it works by unchecking "don't overwrite existing texture folder" option. there was no texture folder before so having this options enabled would normally not do anything but it just prevent the creation of a texture folder.

**Comment by saturday06** [comment] 2024-04-14 18:27
Do you mean that "Extract texture images into the folder" option will not work if there is no texture folder and "don't overwrite existing texture folder" is checked ?

**Comment by saturday06** [comment] 2024-04-14 18:31
In my environment, even in that case, a new folder was created and the textures were extracted. Can you give me a more detailed OS version and Blender version?

**Comment by saturday06** [comment] 2024-07-13 18:21
I tried it in various environments, but I couldn't reproduce it. The issue will close if no new info for 3 months.

**Closed as not planned** 2024-11-11 00:18 UTC
Labels: resolved; will close if no new info for 120 days
