### ISSUE TITLE
Bug report: Major Crash upon export in blender 3.1.0

### ISSUE THREAD

**Issue by jurassicjordan** [saturday06/VRM-Addon-for-Blender#93] opened 2022-03-09 21:40 UTC
**Describe the bug / バグについて**
Causes major crash in Blender 3.1.0

**To Reproduce / バグの再現方法**
1. Have ready model to export
2. Click on file>>export>>VRM
3. Blender then closes

**Expected behavior / 期待する動作**
I expect that the plugin should have exported the vrm file without crashing
どうのようにバグを直してほしいか書いてください。
**Screenshots / スクリーンショット**
何か参考になりそうなスクショがあれば添付してください。
**Desktop (please complete the following information) / PC環境情報**
- OS: Linux Pop!_OS 
- Blender 3.1.0
- Addon Version 1.2.1 and 2.1.13(latest)

**Additional context / なにか他に書いておきたいことはこちらへ**

crashlog:[
# Blender 3.1.0, Commit date: 2022-03-08 18:16, Hash c77597cd0e15

# backtrace
/snap/blender/1925/blender(BLI_system_backtrace+0x20) [0xb33e0a0]
/snap/blender/1925/blender() [0x113105a]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f1cfb8e6520]
/snap/blender/1925/blender(_ZN7blender3gpu14GLStateManager12texture_bindEPNS0_7TextureE16eGPUSamplerStatei+0x28) [0x9e16d68]
/snap/blender/1925/blender() [0x2086207]
/snap/blender/1925/blender() [0x208631b]
/snap/blender/1925/blender(UI_icon_draw_cache_end+0x2a) [0x20895ba]
/snap/blender/1925/blender(UI_block_draw+0x2c2) [0x2064982]
/snap/blender/1925/blender(UI_panels_draw+0xc7) [0x209aef7]
/snap/blender/1925/blender(ED_region_panels_draw+0x76) [0x1a67056]
/snap/blender/1925/blender(ED_region_do_draw+0x851) [0x1a6b061]
/snap/blender/1925/blender(wm_draw_update+0x533) [0x156f763]
/snap/blender/1925/blender(WM_main+0x30) [0x156ccb0]
/snap/blender/1925/blender(main+0x31d) [0x101c4ad]
/lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7f1cfb8cdfd0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f1cfb8ce07d]
/snap/blender/1925/blender() [0x112d96c]

# Python backtrace
]

**Comment by saturday06** [comment] 2022-03-13 01:47
Thanks for reporting! I think https://developer.blender.org/T96294 is the root cause. Please wait for new Blender patch release.

**Comment by saturday06** [comment] 2022-03-20 22:42
Fixed in add-on version 2.3.0. Please retry export ! 💪

**Closed as not planned** 2024-11-03 14:00 UTC
Labels: bug, resolved; will close if no new info for 120 days
